openapi: 3.0.0
info:
  title: Roles API
  description: API for managing roles and their permissions in a task management system.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /roles:
    get:
      summary: List all roles
      responses:
        '200':
          description: A list of roles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Role'

    post:
      summary: Create a new role
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '201':
          description: Role created

  /roles/{roleId}:
    get:
      summary: Get a role by ID
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Role object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Role'
        '404':
          description: Role not found

    put:
      summary: Update a role by ID
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: Role updated
        '404':
          description: Role not found

    delete:
      summary: Delete a role by ID
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Role deleted
        '404':
          description: Role not found

  /roles/{roleId}/grants:
    get:
      summary: List all grants for a specific role
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: List of grants for the specified role
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Grant'

    post:
      summary: Assign a grant to a role
      parameters:
        - name: roleId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Grant'
      responses:
        '201':
          description: Grant assigned to the role

components:
  schemas:
    Role:
      type: object
      properties:
        id:
          type: integer
        roleName:
          type: string
        description:
          type: string

    Grant:
      type: object
      properties:
        grantId:
          type: integer
        grantName:
          type: string
        description:
          type: string
